MAX_AMOUNT = 10000
MAX_COOKING_TIME = 600
MIN_COOKING_TIME = MIN_AMOUNT = 1
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGTH_INGREDIENT_NAME = 128
UNITS_OF_MEASUREMENT = 64

HELP_TEXT_NAME = 'Название рецепта, не более 256 символов.'
HELP_TEXT_COOKING_TIME = 'Время приготовления в минутах.'
HELP_TEXT_UNIT = 'Пример: гр, мл, и т.п.'
