# Generated by Django 3.2.16 on 2024-12-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
