# Generated by Django 3.2.16 on 2024-11-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Используйте только латинские буквы в нижнем регистре,цифры, дефисы и подчеркивания', max_length=32, unique=True, verbose_name='Слаг тега'),
        ),
    ]
