# Generated by Django 3.2.16 on 2024-12-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ingredientinrecipe',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recipe',
            table=None,
        ),
    ]
