# Generated by Django 3.2.16 on 2024-12-08 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241203_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимум один!'), django.core.validators.MaxValueValidator(10000, message='Максимум десять тысяч')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления в минутах.', validators=[django.core.validators.MinValueValidator(1, message='Минимум одна!'), django.core.validators.MaxValueValidator(600, message='Максимум шестьсот')], verbose_name='Время приготовления'),
        ),
    ]
