# Generated by Django 3.2.16 on 2024-10-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20241015_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Используйте только латинские буквы в нижнем регистре, цифры, дефисы и подчеркивания', max_length=256, unique=True, verbose_name='Слаг тега'),
        ),
    ]
