# Generated by Django 3.2.16 on 2024-10-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Обязательно для заполнения, не более 150 символов', max_length=150, unique=True, verbose_name='Никнейм'),
        ),
    ]
