# Generated by Django 3.2.16 on 2024-10-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Обязательно для заполнения, не более 32 символов', max_length=32, verbose_name='Пароль'),
        ),
    ]
