# Generated by Django 3.2.16 on 2024-12-08 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Обязательно для заполнения, не более 150 символов', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Никнейм не должен содержать данные символы - [w.@+-]+$', regex='^[\\w.@+-]+$')], verbose_name='Никнейм'),
        ),
    ]
